import { Command } from "@commander";
import { Maybe } from "../utils.ts";

interface ENewOpts {
    id: string;
}

const action = (name: string, rate: number, initialHours: Maybe<number>, { id }: ENewOpts) => {
    console.log({ name, rate, initialHours, id });
}

export const create = (cmd: Command) => {
    return cmd.command('new')
        .description('Start a new project and set it as the default.')
        .option('-i --id <string>', 'the slug to use for the project. autogenerated by default.')
        .argument('<name>', 'name to use for the project.')
        .argument('<rate>', 'hourly rate', Number)
        .argument('[initial-hours]', 'number of hours to log to start with', Number)
        .action(action);
}