name: build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: build
        run: deno task build
      - name: version
        run: echo "ETU_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ env.ETU_VERSION }}
          tag_name: ${{ env.ETU_VERSION }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./etu
          asset_name: etu-${{ steps.version.outputs.version }}
          asset_content_type: application/x-pie-executable