name: Lint
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - deno.json
      - deno.lock
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - deno.json
      - deno.lock

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Lint code
        run: deno lint
      - name: Check if formatted
        run: deno fmt --check




